### ISSUE TITLE
Unmet peer dependencies for react

### ISSUE THREAD

**Issue by seblau** [shoutem/platform#34]
Cloning a fresh shoutem projects, leads to the following unmet peer dependency warnings: 

![screen shot 2017-11-01 at 21 30 53](https://user-images.githubusercontent.com/3884582/32296391-71e95622-bf4c-11e7-8f3c-c4ba65aae342.png)

The `package.json` comes with `"react": "16.0.0-alpha.6"`. My question is, which version of react is compatible with all the dependencies and should be used here? Can those modules with unmet peer dependencies be updated for react native >= 16.0.0?

**Comment by Vladimir-Vdovic** [comment]
It's just a quirk of semver that community hasn't settled on yet. The thing is that "react": "16.0.0-alpha.6", doesn't match peer dependency requirement "~15.4.0" or "~15.0.0". The issue lies in "-alpha.6" suffix which is treated differently in the semver resolution algorithm. You can read about it [here](https://github.com/npm/node-semver#prerelease-tags). You can safely ignore those warnings.

The resolution would be to not use the alpha tag. Updating those dependencies is only a matter of time.
